// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/vladgrskkh/pr_service/internal/domain"
)

// TeamCreater is an autogenerated mock type for the TeamCreater type
type TeamCreater struct {
	mock.Mock
}

// CreateTeam provides a mock function with given fields: name, members
func (_m *TeamCreater) CreateTeam(name string, members []*domain.User) (*domain.Team, error) {
	ret := _m.Called(name, members)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeam")
	}

	var r0 *domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(string, []*domain.User) (*domain.Team, error)); ok {
		return rf(name, members)
	}
	if rf, ok := ret.Get(0).(func(string, []*domain.User) *domain.Team); ok {
		r0 = rf(name, members)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(string, []*domain.User) error); ok {
		r1 = rf(name, members)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTeamCreater creates a new instance of TeamCreater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamCreater(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamCreater {
	mock := &TeamCreater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
