// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/vladgrskkh/pr_service/internal/domain"
)

// TeamGetter is an autogenerated mock type for the TeamGetter type
type TeamGetter struct {
	mock.Mock
}

// GetTeam provides a mock function with given fields: name
func (_m *TeamGetter) GetTeam(name string) (*domain.Team, []string, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetTeam")
	}

	var r0 *domain.Team
	var r1 []string
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Team, []string, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Team); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(string) []string); ok {
		r1 = rf(name)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]string)
		}
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(name)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewTeamGetter creates a new instance of TeamGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamGetter {
	mock := &TeamGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
