// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/vladgrskkh/pr_service/internal/domain"
)

// PRMerger is an autogenerated mock type for the PRMerger type
type PRMerger struct {
	mock.Mock
}

// MergePullReq provides a mock function with given fields: id
func (_m *PRMerger) MergePullReq(id string) (*domain.PR, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for MergePullReq")
	}

	var r0 *domain.PR
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.PR, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.PR); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PR)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPRMerger creates a new instance of PRMerger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPRMerger(t interface {
	mock.TestingT
	Cleanup(func())
}) *PRMerger {
	mock := &PRMerger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
