// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/vladgrskkh/pr_service/internal/domain"
)

// PullReqReassigner is an autogenerated mock type for the PullReqReassigner type
type PullReqReassigner struct {
	mock.Mock
}

// ReassignReviewer provides a mock function with given fields: prID, userID
func (_m *PullReqReassigner) ReassignReviewer(prID string, userID string) (*domain.PR, error) {
	ret := _m.Called(prID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ReassignReviewer")
	}

	var r0 *domain.PR
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*domain.PR, error)); ok {
		return rf(prID, userID)
	}
	if rf, ok := ret.Get(0).(func(string, string) *domain.PR); ok {
		r0 = rf(prID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PR)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(prID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPullReqReassigner creates a new instance of PullReqReassigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPullReqReassigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *PullReqReassigner {
	mock := &PullReqReassigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
