// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/vladgrskkh/pr_service/internal/domain"
)

// PullReqCreater is an autogenerated mock type for the PullReqCreater type
type PullReqCreater struct {
	mock.Mock
}

// CreatePullReq provides a mock function with given fields: id, name, authorID
func (_m *PullReqCreater) CreatePullReq(id string, name string, authorID string) (*domain.PR, error) {
	ret := _m.Called(id, name, authorID)

	if len(ret) == 0 {
		panic("no return value specified for CreatePullReq")
	}

	var r0 *domain.PR
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (*domain.PR, error)); ok {
		return rf(id, name, authorID)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) *domain.PR); ok {
		r0 = rf(id, name, authorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PR)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(id, name, authorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPullReqCreater creates a new instance of PullReqCreater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPullReqCreater(t interface {
	mock.TestingT
	Cleanup(func())
}) *PullReqCreater {
	mock := &PullReqCreater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
