// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/vladgrskkh/pr_service/internal/domain"
)

// IsActiveSetter is an autogenerated mock type for the IsActiveSetter type
type IsActiveSetter struct {
	mock.Mock
}

// SetIsActiveUser provides a mock function with given fields: id, isActive
func (_m *IsActiveSetter) SetIsActiveUser(id string, isActive bool) (*domain.User, error) {
	ret := _m.Called(id, isActive)

	if len(ret) == 0 {
		panic("no return value specified for SetIsActiveUser")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, bool) (*domain.User, error)); ok {
		return rf(id, isActive)
	}
	if rf, ok := ret.Get(0).(func(string, bool) *domain.User); ok {
		r0 = rf(id, isActive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string, bool) error); ok {
		r1 = rf(id, isActive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIsActiveSetter creates a new instance of IsActiveSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIsActiveSetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *IsActiveSetter {
	mock := &IsActiveSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
