// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MassDeactivater is an autogenerated mock type for the MassDeactivater type
type MassDeactivater struct {
	mock.Mock
}

// MassDeactiveUsers provides a mock function with given fields: teamName, _a1
func (_m *MassDeactivater) MassDeactiveUsers(teamName string, _a1 []string) error {
	ret := _m.Called(teamName, _a1)

	if len(ret) == 0 {
		panic("no return value specified for MassDeactiveUsers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []string) error); ok {
		r0 = rf(teamName, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMassDeactivater creates a new instance of MassDeactivater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMassDeactivater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MassDeactivater {
	mock := &MassDeactivater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
