// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/vladgrskkh/pr_service/internal/domain"
)

// ReviewsGetter is an autogenerated mock type for the ReviewsGetter type
type ReviewsGetter struct {
	mock.Mock
}

// GetReviewByUser provides a mock function with given fields: id
func (_m *ReviewsGetter) GetReviewByUser(id string) ([]*domain.PR, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetReviewByUser")
	}

	var r0 []*domain.PR
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*domain.PR, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) []*domain.PR); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.PR)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReviewsGetter creates a new instance of ReviewsGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReviewsGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReviewsGetter {
	mock := &ReviewsGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
